# Generated by Django 6.1 on 2026-09-04 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("template", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="templatefield",
            name="is_free_text",
            field=models.BooleanField(
                default=False,
                help_text="True if this field is NOT derivable from an HTML table and must be extracted from the email's free-text body by the AI.",
            ),
        ),
    ]
