# Generated by Django 6.1 on 2026-09-05 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("template", "0002_templatefield_is_free_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="template",
            name="is_default",
            field=models.BooleanField(
                default=False,
                help_text="Pre-selected template for one-click extraction from the inbox.",
            ),
        ),
    ]
