# Generated by Django 6.1 on 2026-09-05 05:31

import apps.emails.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emails", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Attachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("filename", models.CharField(max_length=500)),
                ("content_type", models.CharField(blank=True, max_length=200)),
                ("size", models.PositiveIntegerField(default=0)),
                ("file", models.FileField(upload_to=apps.emails.models.attachment_upload_path)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "email",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="emails.email",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
    ]
