# Generated by Django 6.1 on 2026-09-05 14:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emails", "0002_attachment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[("gmail", "Gmail"), ("imap", "IMAP (Outlook, Yahoo, other)")],
                        max_length=20,
                    ),
                ),
                ("email_address", models.EmailField(max_length=254)),
                ("config", models.JSONField(blank=True, default=dict)),
                ("credentials_encrypted", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("last_sync_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_sync_status",
                    models.CharField(
                        blank=True,
                        choices=[("", "Never synced"), ("ok", "OK"), ("error", "Error")],
                        default="",
                        max_length=20,
                    ),
                ),
                ("last_sync_error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_account",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
